modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JensenJ-Modding/YouShallNotDump/issues"
license = "MIT License"

[[mods]]
modId = "youshallnotdump"
version = "${version}"
displayName = "YouShallNotDump"
authors = "JensenJ - Developer"
description = '''
This mod stops f3+s from being used.
'''

[[dependencies.youshallnotdump]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.youshallnotdump]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "youshallnotdump-common.mixins.json"